export const robots = [
  {
    id: 1,
    name: "grahamm",
    username: "BroadcastChannel",
    email: "sincere@april.biz",
  },
  {
    id: 2,
    name: "bashir ishaq",
    username: "Bash",
    email: "bash@april.com",
  },
  {
    id: 3,
    name: "nasir ibrahim",
    username: "nas daily",
    email: "nas@gamil.com",
  },
  {
    id: 4,
    name: "jacob luke",
    username: "Jac",
    email: "jac@gmail.com",
  },
  {
    id: 5,
    name: "braimo jack",
    username: "bray",
    email: "bray@gmail.com",
  },
  {
    id: 6,
    name: "gasss luke",
    username: "gaaac",
    email: "gac@gmail.com",
  },
  {
    id: 7,
    name: "network",
    username: "net",
    email: "net@gmail.com",
  },
  {
    id: 8,
    name: " Aamir mudathir",
    username: "doctor",
    email: "doc@gmail.com",
  },
  {
    id: 9,
    name: "umair mudathir",
    username: "techie",
    email: "techie@gmail.com",
  },
  {
    id: 10,
    name: "Ammar ",
    username: "ammaruru",
    email: "ruru@gmail.com",
  },
  {
    id: 11,
    name: "jack mma",
    username: "BroadcastChannel",
    email: "sincere@april.biz",
  },
  {
    id: 12,
    name: "basit app",
    username: "Bash",
    email: "bash@april.com",
  },
  {
    id: 13,
    name: "vusi",
    username: "nas daily",
    email: "nas@gamil.com",
  },
  {
    id: 14,
    name: "fantamo",
    username: "Jac",
    email: "jac@gmail.com",
  },
  {
    id: 15,
    name: "valentina jack",
    username: "bray",
    email: "bray@gmail.com",
  },
  {
    id: 16,
    name: "kero luke",
    username: "gaaac",
    email: "gac@gmail.com",
  },
  {
    id: 17,
    name: "coal",
    username: "net",
    email: "net@gmail.com",
  },
  {
    id: 18,
    name: " rice chillwell",
    username: "doctor",
    email: "doc@gmail.com",
  },
  {
    id: 19,
    name: "usman",
    username: "techie",
    email: "techie@gmail.com",
  },
  {
    id: 20,
    name: "mustafa ",
    username: "ammaruru",
    email: "ruru@gmail.com",
  },
];
